### ISSUE TITLE
The kernel_x4.pt is not in the github or the google drive

### ISSUE THREAD

**Issue by SungJin-Lee** [csbhr/Deep-Blind-VSR#1]
May I get the kernel_x4.pt for video sr?

**Comment by csbhr** [comment]
You should follow the training strategy in README: https://github.com/csbhr/Deep-Blind-VSR#training

In order to start training quickly, we have uploaded the pretrained kernel net model "kernel_x4.pt" to the google drive. You can download it from the following link:
https://drive.google.com/drive/folders/1y_MGM6YwBZjvkhHlA0OxIFsOL_s5iSRn?usp=sharing

**Comment by SungJin-Lee** [comment]
Ah I didn't find that! Thanks

**Comment by csbhr** [comment]
Go into the google drive link, and you can find it in "pretrained_models" directory.

**Comment by SungJin-Lee** [comment]
Thanks! I found!
